// Shared product data - will be replaced with real data from database
export const mockProducts = [
  // Collections Page Products
  {
    id: 1,
    name: "Elegant Gold Ring",
    slug: "elegant-gold-ring",
    price: 45000,
    originalPrice: 55000,
    discountPercentage: 18,
    category: "Rings",
    purity: "22K",
    weight: 8.5,
    images: ["/ring1.jpg", "/ring2.jpg", "/ring3.jpg"],
    mainImage: "/ring1.jpg",
    isNew: true,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 124,
    shortDescription: "Beautiful handcrafted gold ring with intricate design",
    description: "This exquisite gold ring is meticulously crafted by our skilled artisans using traditional techniques passed down through generations. The intricate design features delicate patterns that catch the light beautifully, making it perfect for special occasions or everyday elegance. Made from pure 22K gold, this ring promises durability and timeless beauty.",
    specifications: {
      material: "22K Gold",
      weight: "8.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Handcrafted with traditional techniques",
      "22K pure gold construction",
      "Intricate design patterns",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for special occasions"
    ]
  },
  {
    id: 2,
    name: "Diamond Necklace",
    slug: "diamond-necklace",
    price: 125000,
    originalPrice: 150000,
    discountPercentage: 17,
    category: "Necklaces",
    purity: "18K",
    weight: 25.2,
    images: ["/necklace1.jpg", "/necklace2.jpg", "/necklace3.jpg"],
    mainImage: "/necklace1.jpg",
    isNew: false,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 89,
    shortDescription: "Stunning diamond necklace perfect for special occasions",
    description: "This magnificent diamond necklace features exquisite craftsmanship and brilliant diamonds that sparkle with every movement. The elegant design combines traditional artistry with modern sophistication, making it a perfect statement piece for any special occasion.",
    specifications: {
      material: "18K Gold with Diamonds",
      weight: "25.2 grams",
      purity: "18 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Brilliant diamond accents",
      "18K gold construction",
      "Elegant chain design",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for special occasions"
    ]
  },
  {
    id: 3,
    name: "Pearl Earrings",
    slug: "pearl-earrings",
    price: 35000,
    originalPrice: 42000,
    discountPercentage: 17,
    category: "Earrings",
    purity: "22K",
    weight: 12.8,
    images: ["/earrings1.jpg", "/earrings2.jpg", "/earrings3.jpg"],
    mainImage: "/earrings1.jpg",
    isNew: true,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: false,
    rating: 4.7,
    reviews: 67,
    shortDescription: "Classic pearl earrings with gold setting",
    description: "These timeless pearl earrings feature lustrous pearls set in elegant 22K gold. The classic design ensures they complement any outfit, from casual to formal occasions. The pearls are carefully selected for their luster and quality.",
    specifications: {
      material: "22K Gold with Pearls",
      weight: "12.8 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Lustrous pearl accents",
      "22K gold setting",
      "Classic timeless design",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for everyday wear"
    ]
  },
  {
    id: 4,
    name: "Gold Bracelet",
    slug: "gold-bracelet",
    price: 28000,
    originalPrice: 35000,
    discountPercentage: 20,
    category: "Bracelets",
    purity: "22K",
    weight: 15.5,
    images: ["/bracelet1.jpg", "/bracelet2.jpg", "/bracelet3.jpg"],
    mainImage: "/bracelet1.jpg",
    isNew: false,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.6,
    reviews: 156,
    shortDescription: "Elegant gold bracelet with traditional patterns",
    description: "This beautiful gold bracelet features intricate traditional patterns that showcase the skill of our master craftsmen. The comfortable fit and elegant design make it perfect for both casual and formal wear.",
    specifications: {
      material: "22K Gold",
      weight: "15.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Traditional pattern design",
      "22K pure gold construction",
      "Comfortable fit",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for everyday wear"
    ]
  },
  {
    id: 5,
    name: "Sapphire Ring",
    slug: "sapphire-ring",
    price: 75000,
    originalPrice: 90000,
    discountPercentage: 17,
    category: "Rings",
    purity: "18K",
    weight: 10.2,
    images: ["/ring2.jpg", "/ring3.jpg", "/ring4.jpg"],
    mainImage: "/ring2.jpg",
    isNew: false,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: false,
    rating: 4.8,
    reviews: 92,
    shortDescription: "Exquisite sapphire ring with diamond accents",
    description: "This stunning sapphire ring features a beautiful blue sapphire surrounded by brilliant diamonds. The elegant design and high-quality gemstones make it a perfect choice for special occasions and engagements.",
    specifications: {
      material: "18K Gold with Sapphire and Diamonds",
      weight: "10.2 grams",
      purity: "18 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Beautiful sapphire center stone",
      "Diamond accents",
      "18K gold construction",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for engagements"
    ]
  },
  {
    id: 6,
    name: "Ruby Pendant",
    slug: "ruby-pendant",
    price: 55000,
    originalPrice: 65000,
    discountPercentage: 15,
    category: "Pendants",
    purity: "22K",
    weight: 18.7,
    images: ["/pendant1.jpg", "/pendant2.jpg", "/pendant3.jpg"],
    mainImage: "/pendant1.jpg",
    isNew: true,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 78,
    shortDescription: "Beautiful ruby pendant with gold chain",
    description: "This exquisite ruby pendant features a stunning red ruby set in elegant 22K gold. The pendant comes with a matching gold chain and is perfect for adding a touch of luxury to any outfit.",
    specifications: {
      material: "22K Gold with Ruby",
      weight: "18.7 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Stunning ruby center stone",
      "22K gold setting and chain",
      "Elegant pendant design",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for special occasions"
    ]
  },
  // New Arrivals Products
  {
    id: 7,
    name: "Modern Gold Ring Set",
    slug: "modern-gold-ring-set",
    price: 35000,
    originalPrice: 42000,
    discountPercentage: 17,
    category: "Rings",
    purity: "22K",
    weight: 8.5,
    images: ["/ring1.jpg", "/ring2.jpg", "/ring3.jpg"],
    mainImage: "/ring1.jpg",
    isNew: true,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: false,
    rating: 4.8,
    reviews: 45,
    shortDescription: "Modern gold ring set with contemporary design",
    description: "This modern gold ring set features a contemporary design that perfectly blends traditional craftsmanship with modern aesthetics. The sleek lines and elegant finish make it perfect for the modern jewelry lover.",
    specifications: {
      material: "22K Gold",
      weight: "8.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Modern contemporary design",
      "22K pure gold construction",
      "Sleek elegant finish",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for modern styling"
    ]
  },
  {
    id: 8,
    name: "Elegant Gold Chain",
    slug: "elegant-gold-chain",
    price: 85000,
    originalPrice: 95000,
    discountPercentage: 11,
    category: "Necklaces",
    purity: "22K",
    weight: 20.5,
    images: ["/necklace1.jpg", "/necklace2.jpg", "/necklace3.jpg"],
    mainImage: "/necklace1.jpg",
    isNew: true,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: false,
    rating: 4.9,
    reviews: 67,
    shortDescription: "Elegant gold chain with sophisticated design",
    description: "This elegant gold chain features a sophisticated design that adds a touch of luxury to any outfit. The fine craftsmanship and attention to detail make it a perfect statement piece.",
    specifications: {
      material: "22K Gold",
      weight: "20.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Sophisticated elegant design",
      "22K pure gold construction",
      "Fine craftsmanship",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect statement piece"
    ]
  },
  {
    id: 9,
    name: "Designer Gold Earrings",
    slug: "designer-gold-earrings",
    price: 55000,
    originalPrice: 65000,
    discountPercentage: 15,
    category: "Earrings",
    purity: "22K",
    weight: 12.8,
    images: ["/earrings1.jpg", "/earrings2.jpg", "/earrings3.jpg"],
    mainImage: "/earrings1.jpg",
    isNew: true,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: false,
    rating: 4.7,
    reviews: 38,
    shortDescription: "Designer gold earrings with unique style",
    description: "These designer gold earrings feature a unique style that sets them apart from conventional designs. The artistic approach and attention to detail make them a perfect choice for those who appreciate distinctive jewelry.",
    specifications: {
      material: "22K Gold",
      weight: "12.8 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Unique designer style",
      "22K pure gold construction",
      "Artistic approach",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for distinctive styling"
    ]
  },
  {
    id: 10,
    name: "Premium Gold Bracelet",
    slug: "premium-gold-bracelet",
    price: 75000,
    originalPrice: 85000,
    discountPercentage: 12,
    category: "Bracelets",
    purity: "22K",
    weight: 18.5,
    images: ["/bracelet1.jpg", "/bracelet2.jpg", "/bracelet3.jpg"],
    mainImage: "/bracelet1.jpg",
    isNew: true,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: false,
    rating: 4.8,
    reviews: 52,
    shortDescription: "Premium gold bracelet with luxury finish",
    description: "This premium gold bracelet features a luxury finish that exudes elegance and sophistication. The high-quality materials and expert craftsmanship make it a perfect addition to any jewelry collection.",
    specifications: {
      material: "22K Gold",
      weight: "18.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Luxury premium finish",
      "22K pure gold construction",
      "Expert craftsmanship",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect luxury addition"
    ]
  },
  // Best Sellers Products
  {
    id: 11,
    name: "Traditional 22K Gold Ring",
    slug: "traditional-22k-gold-ring",
    price: 45000,
    originalPrice: 52000,
    discountPercentage: 13,
    category: "Rings",
    purity: "22K",
    weight: 8.5,
    images: ["/ring1.jpg", "/ring2.jpg", "/ring3.jpg"],
    mainImage: "/ring1.jpg",
    isNew: false,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 127,
    shortDescription: "Traditional 22K gold ring with classic design",
    description: "This traditional 22K gold ring features a classic design that has been loved by customers for generations. The timeless appeal and superior craftsmanship make it a best-seller in our collection.",
    specifications: {
      material: "22K Gold",
      weight: "8.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Traditional classic design",
      "22K pure gold construction",
      "Timeless appeal",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Customer favorite"
    ]
  },
  {
    id: 12,
    name: "Elegant Gold Necklace Set",
    slug: "elegant-gold-necklace-set",
    price: 125000,
    originalPrice: 145000,
    discountPercentage: 14,
    category: "Necklaces",
    purity: "22K",
    weight: 25.2,
    images: ["/necklace1.jpg", "/necklace2.jpg", "/necklace3.jpg"],
    mainImage: "/necklace1.jpg",
    isNew: true,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 89,
    shortDescription: "Elegant gold necklace set for special occasions",
    description: "This elegant gold necklace set is perfect for special occasions. The complete set includes matching pieces that create a cohesive and stunning look for any formal event.",
    specifications: {
      material: "22K Gold",
      weight: "25.2 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Complete elegant set",
      "22K pure gold construction",
      "Perfect for special occasions",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Cohesive matching design"
    ]
  },
  {
    id: 13,
    name: "Bridal Gold Earrings",
    slug: "bridal-gold-earrings",
    price: 85000,
    originalPrice: 95000,
    discountPercentage: 11,
    category: "Earrings",
    purity: "22K",
    weight: 15.8,
    images: ["/earrings1.jpg", "/earrings2.jpg", "/earrings3.jpg"],
    mainImage: "/earrings1.jpg",
    isNew: false,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 156,
    shortDescription: "Bridal gold earrings for wedding occasions",
    description: "These bridal gold earrings are specially designed for wedding occasions. The intricate design and luxurious finish make them perfect for the most important day of your life.",
    specifications: {
      material: "22K Gold",
      weight: "15.8 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Bridal wedding design",
      "22K pure gold construction",
      "Intricate luxurious finish",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for weddings"
    ]
  },
  {
    id: 14,
    name: "Classic Gold Bracelet",
    slug: "classic-gold-bracelet",
    price: 65000,
    originalPrice: 72000,
    discountPercentage: 10,
    category: "Bracelets",
    purity: "22K",
    weight: 16.5,
    images: ["/bracelet1.jpg", "/bracelet2.jpg", "/bracelet3.jpg"],
    mainImage: "/bracelet1.jpg",
    isNew: false,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 94,
    shortDescription: "Classic gold bracelet with traditional appeal",
    description: "This classic gold bracelet features traditional appeal that never goes out of style. The timeless design and superior quality make it a favorite among our customers.",
    specifications: {
      material: "22K Gold",
      weight: "16.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Classic traditional appeal",
      "22K pure gold construction",
      "Timeless design",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Customer favorite"
    ]
  },
  {
    id: 15,
    name: "Modern Gold Pendant",
    slug: "modern-gold-pendant",
    price: 35000,
    originalPrice: 40000,
    discountPercentage: 13,
    category: "Pendants",
    purity: "22K",
    weight: 12.5,
    images: ["/pendant1.jpg", "/pendant2.jpg", "/pendant3.jpg"],
    mainImage: "/pendant1.jpg",
    isNew: true,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 73,
    shortDescription: "Modern gold pendant with contemporary style",
    description: "This modern gold pendant features a contemporary style that appeals to the modern jewelry lover. The sleek design and quality craftsmanship make it a popular choice.",
    specifications: {
      material: "22K Gold",
      weight: "12.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Modern contemporary style",
      "22K pure gold construction",
      "Sleek design",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Popular choice"
    ]
  },
  {
    id: 16,
    name: "Royal Gold Bangle Set",
    slug: "royal-gold-bangle-set",
    price: 95000,
    originalPrice: 110000,
    discountPercentage: 14,
    category: "Bangles",
    purity: "22K",
    weight: 22.5,
    images: ["/bracelet1.jpg", "/bracelet2.jpg", "/bracelet3.jpg"],
    mainImage: "/bracelet1.jpg",
    isNew: false,
    isBestSeller: true,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 112,
    shortDescription: "Royal gold bangle set with regal design",
    description: "This royal gold bangle set features a regal design that exudes luxury and elegance. The complete set is perfect for special occasions and formal events.",
    specifications: {
      material: "22K Gold",
      weight: "22.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Royal regal design",
      "22K pure gold construction",
      "Complete bangle set",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for special occasions"
    ]
  },
  // Discounted Products
  {
    id: 17,
    name: "Wedding Gold Ring Set",
    slug: "wedding-gold-ring-set",
    price: 85000,
    originalPrice: 120000,
    discountPercentage: 29,
    category: "Rings",
    purity: "22K",
    weight: 18.5,
    images: ["/ring1.jpg", "/ring2.jpg", "/ring3.jpg"],
    mainImage: "/ring1.jpg",
    isNew: false,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 89,
    shortDescription: "Wedding gold ring set with special discount",
    description: "This wedding gold ring set is available at a special discount. The complete set includes matching rings perfect for your special day, crafted with the finest materials and attention to detail.",
    specifications: {
      material: "22K Gold",
      weight: "18.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Complete wedding ring set",
      "22K pure gold construction",
      "Special discount price",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for weddings"
    ]
  },
  {
    id: 18,
    name: "Traditional Gold Necklace",
    slug: "traditional-gold-necklace",
    price: 95000,
    originalPrice: 135000,
    discountPercentage: 30,
    category: "Necklaces",
    purity: "22K",
    weight: 28.5,
    images: ["/necklace1.jpg", "/necklace2.jpg", "/necklace3.jpg"],
    mainImage: "/necklace1.jpg",
    isNew: false,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 67,
    shortDescription: "Traditional gold necklace with maximum discount",
    description: "This traditional gold necklace is available with maximum discount. The classic design and superior craftsmanship make it a perfect choice for those who appreciate traditional jewelry.",
    specifications: {
      material: "22K Gold",
      weight: "28.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Traditional classic design",
      "22K pure gold construction",
      "Maximum discount available",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect traditional choice"
    ]
  },
  {
    id: 19,
    name: "Bridal Gold Earrings",
    slug: "bridal-gold-earrings-discounted",
    price: 65000,
    originalPrice: 95000,
    discountPercentage: 32,
    category: "Earrings",
    purity: "22K",
    weight: 14.5,
    images: ["/earrings1.jpg", "/earrings2.jpg", "/earrings3.jpg"],
    mainImage: "/earrings1.jpg",
    isNew: false,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 112,
    shortDescription: "Bridal gold earrings with special offer",
    description: "These bridal gold earrings are available with a special offer. The intricate design and luxurious finish make them perfect for your special day at an unbeatable price.",
    specifications: {
      material: "22K Gold",
      weight: "14.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Bridal special design",
      "22K pure gold construction",
      "Special offer price",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect for special day"
    ]
  },
  {
    id: 20,
    name: "Classic Gold Bracelet",
    slug: "classic-gold-bracelet-discounted",
    price: 45000,
    originalPrice: 65000,
    discountPercentage: 31,
    category: "Bracelets",
    purity: "22K",
    weight: 14.5,
    images: ["/bracelet1.jpg", "/bracelet2.jpg", "/bracelet3.jpg"],
    mainImage: "/bracelet1.jpg",
    isNew: false,
    isBestSeller: false,
    isDiscounted: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 78,
    shortDescription: "Classic gold bracelet with amazing discount",
    description: "This classic gold bracelet is available with an amazing discount. The traditional design and quality craftsmanship make it a perfect addition to your jewelry collection at an unbeatable price.",
    specifications: {
      material: "22K Gold",
      weight: "14.5 grams",
      purity: "22 Karat",
      finish: "Polished",
      warranty: "Lifetime Polish Service",
      origin: "Handcrafted in India"
    },
    features: [
      "Classic traditional design",
      "22K pure gold construction",
      "Amazing discount price",
      "Lifetime polish service included",
      "Comes with authenticity certificate",
      "Perfect collection addition"
    ]
  }
];

// Get emoji for product category
export const getCategoryEmoji = (category: string) => {
  const emojiMap: { [key: string]: string } = {
    'Rings': '💍',
    'Necklaces': '💎',
    'Earrings': '✨',
    'Bracelets': '🔗',
    'Pendants': '💫',
    'Bangles': '🔔'
  };
  return emojiMap[category] || '💍';
};

// Get related products (excluding current product)
export const getRelatedProducts = (currentProduct: typeof mockProducts[0]) => {
  return mockProducts
    .filter(p => p.id !== currentProduct.id)
    .slice(0, 3);
};
